name: Build App

on:
  push:
    branches: ["master"]

jobs:
  Build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${ secrets.EXPO_TOKEN }" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install packages
        run: yarn

      # - name: Build app
      #   run: eas update --auto
