name: Build App

on:
  push:
    branches: ["master"]

jobs:
  Build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install packages
        run: yarn

      - name: Build app
        run: eas update --auto
